import type { WeddingSettings } from "./types";

export const DEFAULT_SETTINGS: WeddingSettings = {
  id: "main",
  bride_full_name: "Carolina Elizabeth Vega Carrera",
  bride_display_name: "Carolina",
  groom_full_name: "Esthefano Gonzalo Morales Campaña",
  groom_display_name: "Esthefano",
  wedding_date: "2027-02-06",
  wedding_time: "18:00",
  ceremony_place: "Catedral de Antofagasta",
  ceremony_city: "Antofagasta, Chile",
  ceremony_address: "Catedral de Antofagasta, Antofagasta, Chile",
  maps_url: "https://www.google.com/maps/search/?api=1&query=Catedral%20de%20Antofagasta%2C%20Antofagasta%2C%20Chile",
  hero_subtitle: "Con la bendición de Dios y el amor de nuestras familias",
  invitation_phrase: "Tenemos el honor de invitarte a celebrar nuestra unión religiosa. Queremos que seas parte de este momento sagrado, alegre y profundamente especial en nuestras vidas.",
  meaning_title: "Un día con sentido",
  meaning_text: "Este encuentro no es solo una celebración; es el inicio de una nueva vida juntos, frente a Dios, nuestras familias y las personas que han acompañado nuestra historia.",
  dress_code: "Formal elegante",
  dress_note: "Te invitamos a vestir con tonos sobrios y elegantes para acompañar la solemnidad y alegría de este día.",
  gift_title: "Lluvia de sobres",
  gift_text: "Tu presencia es nuestro mayor regalo. Si deseas acompañarnos con un detalle, hemos preparado una lluvia de sobres como alternativa a los regalos físicos.",
  bank_name: "Banco por definir",
  bank_account_type: "Cuenta por definir",
  bank_account_number: "Número por definir",
  bank_account_holder: "Nombre por definir",
  bank_account_rut: "RUT por definir",
  bank_account_email: "Correo por definir",
  album_title: "Álbum de recuerdos",
  album_text: "Durante la celebración podrás compartir tus fotos y videos para guardar juntos los mejores recuerdos de este día.",
  album_upload_url: "https://www.instagram.com/",
  whatsapp_one: "56926301822",
  whatsapp_two: "56988215400",
  story_title: "Nuestra historia",
  story_text: "Nuestra historia comenzó con pequeños momentos que fueron creciendo hasta convertirse en una promesa de amor, respeto y compañía para toda la vida.",
  closing_title: "Gracias por ser parte de nuestras vidas",
  closing_text: "Gracias por acompañarnos con tu cariño, oración y presencia. Será una alegría inmensa compartir contigo este día tan especial.",
  music_url: "/music/wedding-song.mp3",
  hero_image_url: "/photos/wedding-hero.svg",
  meaning_image_url: "/photos/wedding-meaning.svg",
  story_image_1_url: "/photos/story-1.svg",
  story_image_2_url: "/photos/story-2.svg",
  story_image_3_url: "/photos/story-3.svg"
};
